// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// SessionVerifier is an autogenerated mock type for the SessionVerifier type
type SessionVerifier struct {
	mock.Mock
}

// GetUserID provides a mock function with given fields: c
func (_m *SessionVerifier) GetUserID(c *gin.Context) string {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetUserID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(*gin.Context) string); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// VerifySession provides a mock function with given fields: c
func (_m *SessionVerifier) VerifySession(c *gin.Context) {
	_m.Called(c)
}

// NewSessionVerifier creates a new instance of SessionVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionVerifier {
	mock := &SessionVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
