# Services necessary for local dev

services:
  fake_go_postgres_svc:
    container_name: fake_go_postgres_prod_ctnr
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secretprod
    volumes:
      - db/fake-prod-db-init:/docker-entrypoint-initdb.d

  fake_go_app_svc:
    depends_on:
      - fake_go_postgres_svc
    container_name: fake_go_app_ctnr
    image: fullstackgonuxtjs
    environment:
      - ENV=production
    ports:
      - "8080:8080"
    volumes:
      - "$HOME/.ejson_keys:/opt/ejson/keys"

  # From: https://supertokens.com/docs/emailpassword/pre-built-ui/setup/core/with-docker#docker-compose-file
  fake_go_supertokens_svc:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:9.2.0
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRESQL_CONNECTION_URI: "postgresql://supertokens:supertokens@postgres_svc:5432/supertokens"
    restart: unless-stopped
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5